name: pme
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib             # plotting library
  - texlive-core           # full LaTeX engine
  - dvipng                 # DVI→PNG converter
  - ghostscript            # PostScript interpreter
  - pip                    # ensure pip is available
  - pip:
    - git+https://github.com/google-deepmind/jax_privacy
    - jax>=0.5.1
    - jaxlib>=0.5.1
